export enum AnalyticEmitEvent {
  ANALYTIC_NEW_COMMING_RETURN = "ANALYTIC_NEW_COMMING_RETURN",
  ANALYTIC_AGE = "ANALYTIC_AGE",
  ANALYTIC_DEVICE = "ANALYTIC_DEVICE",
  ANALYTIC_GENDER = "ANALYTIC_GENDER",
  ANALYTIC_VEHICLE_TYPE = "ANALYTIC_VEHICLE_TYPE",
  ANALYTIC_TOP_PRODUCT_SERVICE = "ANALYTIC_TOP_PRODUCT_SERVICE",
  ANALYTIC_TOP_ACTIVE_USER = "ANALYTIC_TOP_ACTIVE_USER",
  ANALYTIC_UNIQUE_VISITOR = "ANALYTIC_UNIQUE_VISITOR",
}

export enum AnalyticReceiveEvent {
  ANALYTIC_NEW_COMMING_RETURN = "ANALYTIC_NEW_COMMING_RETURN",
  ANALYTIC_AGE = "ANALYTIC_AGE",
  ANALYTIC_DEVICE = "ANALYTIC_DEVICE",
  ANALYTIC_GENDER = "ANALYTIC_GENDER",
  ANALYTIC_VEHICLE_TYPE = "ANALYTIC_VEHICLE_TYPE",
  ANALYTIC_TOP_PRODUCT_SERVICE = "ANALYTIC_TOP_PRODUCT_SERVICE",
  ANALYTIC_TOP_ACTIVE_USER = "ANALYTIC_TOP_ACTIVE_USER",
  ANALYTIC_UNIQUE_VISITOR = "ANALYTIC_UNIQUE_VISITOR",
}
