version: 2.1
jobs:
  build_deploy_dev:
    machine:
      image: ubuntu-2004:2023.02.1
    environment:
       DOCKER_IMAGE_NAME: autoaidess
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update && sudo apt-get -y install apt-transport-https ca-certificates curl gnupg lsb-release sshpass
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update && sudo apt-get -y install docker-ce docker-ce-cli containerd.io
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_IMAGE_NAME:stage .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag $DOCKER_IMAGE_NAME:stage $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
      - add_ssh_keys:
          fingerprints:
            - "70:ee:cd:14:e5:fe:9a:af:98:32:2d:e9:f0:5c:f3:65"
      - run:
          name: SSH to server and deploy Docker image
          command: |
            CONTAINER_ID=$(sshpass -p "$SSH_PASSWORD" ssh $SSH_USERNAME@$SSH_HOST "docker ps --filter 'publish=4000' --format '{{.ID}}'")

            if [ ! -z "$CONTAINER_ID" ]; then
              sshpass -p "$SSH_PASSWORD" ssh $SSH_USERNAME@$SSH_HOST "docker stop $CONTAINER_ID && docker rm $CONTAINER_ID"
            fi

            sshpass -p "$SSH_PASSWORD" ssh $SSH_USERNAME@$SSH_HOST "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker pull $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME && docker run -d -p 4000:4000 $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME"


workflows:
  version: 2
  build:
    jobs:
      - build_deploy_dev
