export enum DashboardEmittingEvents {
  SALE_FLOW_WITH_SERVICE_SCHEDULE_VS_EMERGENT_REQUEST = "DASHBOARD_SALE_FLOW_WITH_SERVICE_SCHEDULE_VS_EMERGENT_REQUEST",
  INVOICE_FLOW_BY_HOURS = "DASHBOARD_INVOICE_FLOW_BY_HOURS",
  TOP_PROVINCE_USE_SERVICE_SCHEDULE_AND_EMERGENT_REQUEST = "DASHBOARD_TOP_PROVINCE_USE_SERVICE_SCHEDULE_AND_EMERGENT_REQUEST",
  TOP_CHANNEL = "DASHBOARD_TOP_CHANNEL",
  RECENT_ACTIVITY = "DASHBOARD_RECENT_ACTIVITY",
  INCOME_EXPENSES = "DASHBOARD_INCOME_EXPENSES",
  ACTIVE_USERS = "DASHBOARD_ACTIVE_USERS",
  TOTAL_INCOME_FROM_GARAGE = "DASHBOARD_TOTAL_INCOME_FROM_GARAGE",
  TOTAL_INCOME_FROM_CUSTOMERS = "DASHBOARD_TOTAL_INCOME_FROM_CUSTOMERS",
}

export enum DashboardReceivingEvents {
  SALE_FLOW_WITH_SERVICE_SCHEDULE_VS_EMERGENT_REQUEST = "DASHBOARD_SALE_FLOW_WITH_SERVICE_SCHEDULE_VS_EMERGENT_REQUEST",
  INVOICE_FLOW_BY_HOURS = "DASHBOARD_INVOICE_FLOW_BY_HOURS",
  TOP_PROVINCE_USE_SERVICE_SCHEDULE_AND_EMERGENT_REQUEST = "DASHBOARD_TOP_PROVINCE_USE_SERVICE_SCHEDULE_AND_EMERGENT_REQUEST",
  TOP_CHANNEL = "DASHBOARD_TOP_CHANNEL",
  RECENT_ACTIVITY = "DASHBOARD_RECENT_ACTIVITY",
  INCOME_EXPENSES = "DASHBOARD_INCOME_EXPENSES",
  ACTIVE_USERS = "DASHBOARD_ACTIVE_USERS",
  TOTAL_INCOME_FROM_GARAGE = "DASHBOARD_TOTAL_INCOME_FROM_GARAGE",
  TOTAL_INCOME_FROM_CUSTOMERS = "DASHBOARD_TOTAL_INCOME_FROM_CUSTOMERS",
}
